name: test
channels:
  - conda-forge
dependencies:
  - python
  # tests
  - pytest
  - pytest-cov
  - geopandas-base
  - pyogrio
  - pip
  - pip:
      - git+https://github.com/fatiando/pooch.git@main
